#!/usr/bin/env python3
"""Regenerate the architecture-atlas diagrams and freshness manifest.

Reads first-party imports out of ``src/`` with the stdlib ``ast`` parser (no
third-party dependency) and emits deterministic Mermaid artifacts:

- ``docs/architecture/module_deps.mmd`` — package-level import graph,
- ``docs/architecture/data_flow.mmd`` — ingest → features → model →
  backtest/paper → receipt,
- ``docs/architecture/paper_loop_sequence.mmd`` — paper/shadow event loop,
- ``docs/architecture/manifest.json`` — sorted module list + package edges,
- generated blocks spliced into ``docs/ARCHITECTURE_ATLAS.md`` between
  ``<!-- BEGIN GENERATED: <name> -->`` / ``<!-- END GENERATED: <name> -->``
  markers.

``--check`` regenerates everything in memory and exits 1 when any committed
artifact (``.mmd``, ``manifest.json``, or an embedded atlas block) is stale.
Determinism contract: every emitted collection is sorted, so byte-for-byte
comparison is stable across runs and platforms.

Curated diagrams (data flow, paper loop) are declared in this file but every
node carries a ``module::symbol`` anchor that is verified against the parsed
source — renaming or deleting an anchored symbol fails generation (and
``--check``), so the pictures cannot silently drift from the code they claim
to describe.
"""

from __future__ import annotations

import argparse
import ast
import json
import sys
from collections import Counter
from pathlib import Path

FIRST_PARTY_ROOTS = ("quant_fund", "fx1")
SCHEMA_VERSION = 1
GENERATOR = "scripts/gen_arch_diagrams.py"
ARCH_DIR = Path("docs") / "architecture"
ATLAS_DOC = Path("docs") / "ARCHITECTURE_ATLAS.md"

GENERATED_HEADER = "%% Generated by scripts/gen_arch_diagrams.py — do not edit by hand."


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


# ---------------------------------------------------------------------------
# Import scanning
# ---------------------------------------------------------------------------


def iter_source_modules(src: Path) -> list[tuple[str, Path, bool]]:
    """Return sorted ``(dotted_module, repo-relative path, is_package)``."""
    out: list[tuple[str, Path, bool]] = []
    for path in sorted(src.rglob("*.py")):
        rel = path.relative_to(src).with_suffix("")
        parts = list(rel.parts)
        is_package = parts[-1] == "__init__"
        if is_package:
            parts = parts[:-1]
        if parts:
            out.append((".".join(parts), path, is_package))
    return sorted(out)


def _resolve_from(module: str, level: int, name: str | None, is_package: bool) -> str:
    """Resolve ``from <name> import ...`` at ``level`` inside ``module``.

    ``level == 0`` is absolute. For relative imports, level 1 is the current
    package: the module's parent for a regular module, the package itself for
    an ``__init__``.
    """
    if level == 0:
        return name or ""
    parts = module.split(".")
    drop = level - (1 if is_package else 0)
    base = parts[: len(parts) - drop]
    return ".".join(base + ([name] if name else []))


def parse_first_party_imports(
    path: Path, module: str, is_package: bool, known_modules: set[str]
) -> set[str]:
    """First-party import targets referenced by ``path`` (stdlib ast only).

    Includes function-level imports: optional/lazy dependencies (e.g. the
    W1 ``quant_fund.pit`` vault) are still real edges in the source.

    One edge per import alias: ``from a.b import c`` resolves to ``a.b.c``
    when that submodule exists, else to ``a.b``.
    """
    tree = ast.parse(path.read_text(encoding="utf-8"))
    targets: set[str] = set()
    for node in ast.walk(tree):
        candidates: list[str] = []
        if isinstance(node, ast.Import):
            candidates = [alias.name for alias in node.names]
        elif isinstance(node, ast.ImportFrom):
            base = _resolve_from(module, node.level, node.module, is_package)
            if base:
                candidates = [
                    f"{base}.{alias.name}" if f"{base}.{alias.name}" in known_modules else base
                    for alias in node.names
                ]
        for cand in candidates:
            if cand.split(".")[0] in FIRST_PARTY_ROOTS:
                targets.add(cand)
    return targets


def package_of(module: str) -> str:
    """Aggregate a dotted module to its second-level package node."""
    parts = module.split(".")
    if len(parts) > 1 and parts[0] in FIRST_PARTY_ROOTS:
        return ".".join(parts[:2])
    return parts[0]


def collect_graph(
    root: Path,
) -> tuple[list[str], Counter[tuple[str, str]], set[tuple[str, str]]]:
    """Scan ``src``; return (sorted modules, package edge counts, module edges).

    Package edges count distinct first-party modules imported per package
    pair. Module edges are the exact ``(importer, imported)`` pairs — the
    manifest stores them so ``--check`` detects any first-party import
    change, including moves within a package.
    """
    src = root / "src"
    modules = iter_source_modules(src)
    known_modules = {name for name, _, _ in modules}
    edges: Counter[tuple[str, str]] = Counter()
    module_edges: set[tuple[str, str]] = set()
    for name, path, is_package in modules:
        src_pkg = package_of(name)
        for target in parse_first_party_imports(path, name, is_package, known_modules):
            edges[(src_pkg, package_of(target))] += 1
            module_edges.add((name, target))
    return [name for name, _, _ in modules], edges, module_edges


# ---------------------------------------------------------------------------
# Symbol anchors for curated diagrams
# ---------------------------------------------------------------------------


def _top_level_symbols(path: Path) -> set[str]:
    """Top-level defs/classes/assignments plus ``Class.method`` members."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    names: set[str] = set()
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            names.add(node.name)
        elif isinstance(node, ast.ClassDef):
            names.add(node.name)
            for sub in node.body:
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    names.add(f"{node.name}.{sub.name}")
        elif isinstance(node, ast.Assign):
            for tgt in node.targets:
                if isinstance(tgt, ast.Name):
                    names.add(tgt.id)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            names.add(node.target.id)
    return names


def verify_anchors(root: Path) -> list[str]:
    """Return a list of errors for missing modules/symbols (empty when clean)."""
    errors: list[str] = []
    cache: dict[str, set[str]] = {}
    for anchor, (rel, symbol) in sorted(ANCHORS.items()):
        path = root / rel
        if not path.is_file():
            errors.append(f"{anchor}: module file missing: {rel}")
            continue
        if symbol == "*":
            continue
        if rel not in cache:
            cache[rel] = _top_level_symbols(path)
        if symbol not in cache[rel]:
            errors.append(f"{anchor}: {symbol} not defined at top level of {rel}")
    return errors


# Anchors bind curated-diagram nodes to real code. ``*`` = module exists.
ANCHORS: dict[str, tuple[str, str]] = {
    "cli_main": ("src/quant_fund/cli/_app.py", "app"),
    "cli_paper": ("src/quant_fund/cli/ops_cmds.py", "paper"),
    "make_provider": ("src/quant_fund/data/ingest.py", "make_provider"),
    "ingest": ("src/quant_fund/data/ingest.py", "ingest"),
    "lake": ("src/quant_fund/data/lake.py", "Lake"),
    "adjust_prices": ("src/quant_fund/data/corporate_actions.py", "adjust_prices"),
    "membership": ("src/quant_fund/data/universe.py", "build_membership_panel"),
    "security_master": ("src/quant_fund/data/security_master.py", "attach_master_attributes"),
    "pit_validate": ("src/quant_fund/data/point_in_time.py", "validate_feature_frame"),
    "build_features": ("src/quant_fund/features/engine.py", "build_features"),
    "feature_version": ("src/quant_fund/features/metadata.py", "FEATURE_SET_VERSION"),
    "build_labels": ("src/quant_fund/labels/engine.py", "build_labels"),
    "build_gold": ("src/quant_fund/pipeline/dataset.py", "build_gold"),
    "panel": ("src/quant_fund/pipeline/dataset.py", "panel"),
    "train": ("src/quant_fund/pipeline/train.py", "train_ranking"),
    "forecast_asof": ("src/quant_fund/pipeline/forecast.py", "forecast_asof"),
    "optimize_asof": ("src/quant_fund/pipeline/forecast.py", "optimize_asof"),
    "causal_weights": ("src/quant_fund/pipeline/forecast.py", "build_causal_weight_panel"),
    "market_overlay": ("src/quant_fund/pipeline/forecast.py", "market_risk_overlay_asof"),
    "market_state": ("src/quant_fund/schemas/forecast.py", "MarketState"),
    "fuse_signals": ("src/quant_fund/fusion/engine.py", "fuse_signals"),
    "optimizer": ("src/quant_fund/portfolio/optimizer.py", "optimize_mean_variance"),
    "risk_gate": ("src/quant_fund/portfolio/risk_gate.py", "check_order"),
    "total_cost": ("src/quant_fund/execution/costs.py", "total_cost"),
    "sim_broker": ("src/quant_fund/execution/simulated_broker.py", "SimulatedBroker"),
    "broker_submit": ("src/quant_fund/execution/simulated_broker.py", "SimulatedBroker.submit"),
    "broker_t2o": (
        "src/quant_fund/execution/simulated_broker.py",
        "SimulatedBroker.target_to_orders",
    ),
    "run_backtest": ("src/quant_fund/backtest/engine.py", "run_backtest"),
    "kill_switch": ("src/quant_fund/monitoring/kill_switch.py", "KillSwitch"),
    "paper_loop": ("src/quant_fund/paper/loop.py", "run_paper_loop"),
    "replay_clock": ("src/quant_fund/paper/clock.py", "ReplayClock"),
    "wall_clock": ("src/quant_fund/paper/clock.py", "WallClock"),
    "ledger": ("src/quant_fund/paper/ledger.py", "PaperLedger"),
    "ledger_flush": ("src/quant_fund/paper/ledger.py", "PaperLedger.flush"),
    "ledger_broker_state": ("src/quant_fund/paper/ledger.py", "PaperLedger.save_broker_state"),
    "promo_dry_run": ("src/quant_fund/paper/ledger.py", "promotion_dry_run"),
    "run_research": ("src/quant_fund/research/agent.py", "run_research"),
    "verify_research": ("src/quant_fund/research/verify.py", "verify_research_artifact"),
    "validate_candidate": ("src/quant_fund/validation/gates.py", "validate_candidate"),
    "sim_live": ("src/quant_fund/paper/sim_live.py", "run_sim_live"),
    "fx1_cli": ("src/fx1/cli.py", "app"),
    "fx1_corpus": ("src/fx1/data/corpus.py", "*"),
    "fx1_honesty": ("src/fx1/honesty.py", "FORBIDDEN_HEADLINE_TOKENS"),
    "catalog": (
        "src/quant_fund/research/catalog/constants.py",
        "FORBIDDEN_RESEARCH_METRIC_KEYS",
    ),
}


# ---------------------------------------------------------------------------
# Renderers (all deterministic — every collection is sorted)
# ---------------------------------------------------------------------------


def _mmd_id(package: str) -> str:
    return package.replace(".", "_").replace("-", "_")


def render_module_deps(modules: list[str], edges: Counter[tuple[str, str]]) -> str:
    known_pkgs = {package_of(m) for m in modules}
    qf = sorted(p for p in known_pkgs if p == "quant_fund" or p.startswith("quant_fund."))
    fx = sorted(p for p in known_pkgs if p == "fx1" or p.startswith("fx1."))
    ghost = sorted(
        {dst for (_, dst) in edges if dst not in known_pkgs}
        | {src for (src, _) in edges if src not in known_pkgs}
    )
    lines = [GENERATED_HEADER, "flowchart LR"]
    for group, title in (("quant_fund", "quant_fund (harness)"), ("fx1", "fx1 (model project)")):
        members = qf if group == "quant_fund" else fx
        lines.append(f'  subgraph {group}["{title}"]')
        for pkg in members:
            lines.append(f'    {_mmd_id(pkg)}["{pkg}"]')
        lines.append("  end")
    for pkg in ghost:
        lines.append(f'  {_mmd_id(pkg)}["{pkg}"]:::ghost')
    for (src, dst), count in sorted(edges.items()):
        if src == dst:
            continue
        lines.append(f"  {_mmd_id(src)} -->|{count}| {_mmd_id(dst)}")
    lines += [
        "  classDef ghost stroke-dasharray: 5 5,color:#888",
        "  %% ghost nodes are lazily referenced packages absent from this tree",
    ]
    return "\n".join(lines) + "\n"


def render_data_flow() -> str:
    """ingest → features → model → backtest/paper → receipt. Anchored nodes."""
    return (
        "\n".join(
            [
                GENERATED_HEADER,
                "flowchart LR",
                '  subgraph SRC["point-in-time data"]',
                '    prov["make_provider()\\nsynthetic | file | hf_ohlcv_1m | public sources"]',
                '    ingest["ingest()\\nbronze/silver parquet + data_manifest.json"]',
                '    adj["adjust_prices() / apply_listing_actions()\\ncorporate actions"]',
                '    univ["build_membership_panel()\\nPIT universe"]',
                "  end",
                '  subgraph GOLD["gold panel"]',
                '    feats["build_features()\\nFEATURE_SET_VERSION stamp"]',
                '    labs["build_labels()\\nforward-looking, never features"]',
                '    gold["build_gold() / panel()\\nmembership re-validated on cached gold"]',
                "  end",
                '  subgraph MODEL["forecast stack"]',
                '    train["train_* families\\npipeline/train.py → joblib artifacts"]',
                '    fcst["forecast_asof()\\nMarketState + CQR intervals"]',
                '    fuse["fuse_signals()\\ntransparent fusion"]',
                "  end",
                '  subgraph ALLOC["allocation + risk"]',
                '    opt["optimize_mean_variance()\\ninfeasible → diagnostics, no relaxation"]',
                '    gate["check_order()\\ndeterministic pre-trade risk gate"]',
                '    cost["total_cost()\\ncommission + spread + impact"]',
                "  end",
                '  subgraph SIM["simulation (no live orders)"]',
                '    bt["run_backtest()\\nevent-driven, next-open fills"]',
                '    pl["run_paper_loop()\\nchampion + shadow slots"]',
                "  end",
                '  subgraph EVID["evidence"]',
                '    nb["run_research()\\nsealed notebook + runs/<id>.json"]',
                '    ver["verify_research_artifact()\\nfail-closed recompute"]',
                '    prom["validate_candidate()\\nreceipt-bound promotion gates"]',
                "  end",
                "  prov --> ingest --> adj --> univ",
                "  univ --> feats --> gold",
                "  univ --> labs --> gold",
                "  gold --> train --> fcst",
                "  fcst --> fuse --> opt --> gate",
                "  gate --> bt",
                "  gate --> pl",
                "  cost --> bt",
                "  cost --> pl",
                "  bt --> nb",
                "  pl --> nb",
                "  nb --> ver --> prom",
            ]
        )
        + "\n"
    )


def render_paper_loop() -> str:
    """Sequence diagram of ``run_paper_loop`` (champion + shadow slots)."""
    return (
        "\n".join(
            [
                GENERATED_HEADER,
                "sequenceDiagram",
                "  autonumber",
                "  participant CLI as dipcatcher paper",
                "  participant Loop as run_paper_loop",
                "  participant Clock as ReplayClock / WallClock",
                "    participant W as WeightFn (weights panel)",
                "    participant CB as SimulatedBroker champion",
                "    participant SB as SimulatedBroker shadow",
                "    participant KS as KillSwitch",
                "    participant RG as check_order (risk gate)",
                "    participant L as PaperLedger",
                "  CLI->>Loop: run_paper_loop(bars, cfg, champion/shadow weights)",
                "  opt resume",
                "    Loop->>L: load_broker_state(run_id)",
                "    L-->>Loop: prior champion/shadow state + cursors",
                "    Loop->>Loop: verify resume_fingerprint over bar prefix",
                "  end",
                "  Loop->>L: set_meta(data_source, label=PAPER_SIMULATED)",
                "  Loop->>Clock: ReplayClock(decision_dates)",
                "  loop each decision date t",
                "    Loop->>Clock: tick() -> t",
                "    Loop->>Loop: exec_dt = next bar open (FillConvention.NEXT_OPEN)",
                "    Loop->>CB: mark(pretrade marks: fresh opens + bounded carry)",
                "    Loop->>SB: mark(pretrade marks)",
                "    Loop->>W: champion_fn(t, cfg)",
                "    W-->>Loop: target weights",
                "    Loop->>W: shadow_fn(t, cfg) (optional)",
                "    Loop->>Loop: L1 divergence champion vs shadow",
                "    Loop->>CB: nav(pretrade_marks); break if <= 0",
                "    Loop->>Loop: market_risk_overlay_asof(cfg, bars, t)",
                "    Loop->>CB: target_to_orders(targets, marks)",
                "    loop each order",
                "      CB->>KS: assert_new_orders_allowed()",
                "      KS--xCB: KillSwitchActive when state != ENABLED",
                "      CB->>RG: check_order(nav, gross, net, participation, vol)",
                "      RG--xCB: RiskGateRejected on breach (counted)",
                "      CB->>CB: total_cost() then cash/shares update",
                "      CB-->>Loop: OrderRecord (fill or reject_reason)",
                "    end",
                "    Loop->>L: record_orders(step_recs, exec_dt)",
                "    Loop->>CB: mark(close marks) + exposures",
                "    Loop->>L: record_snapshot / record_shadow_equity",
                "    Loop->>L: flush()",
                "    Loop->>L: save_broker_state(cursor published LAST)",
                "  end",
                "  Loop->>L: promotion_dry_run() -> write_promotion_dry_run",
                "  Loop->>L: write_analytics_export + validate",
                "  Loop-->>CLI: PaperLoopResult{research_only, live_pnl_claim: false, paths}",
            ]
        )
        + "\n"
    )


def render_coverage(modules: list[str], edges: Counter[tuple[str, str]]) -> str:
    counts: Counter[str] = Counter(package_of(m) for m in modules)
    lines = ["| Package | Modules |", "|---|---|"]
    for pkg in sorted(counts):
        lines.append(f"| `{pkg}` | {counts[pkg]} |")
    n_edges = sum(1 for (s, d) in edges if s != d)
    lines.append("")
    lines.append(f"- Modules scanned: **{len(modules)}**")
    lines.append(f"- Packages: **{len(counts)}**")
    lines.append(f"- Cross-package import edges: **{n_edges}**")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Artifact assembly
# ---------------------------------------------------------------------------


def generated_artifacts(root: Path) -> dict[str, str]:
    """Return ``{repo-relative path: content}`` for every generated file."""
    modules, edges, module_edges = collect_graph(root)
    return {
        str(ARCH_DIR / "module_deps.mmd"): render_module_deps(modules, edges),
        str(ARCH_DIR / "data_flow.mmd"): render_data_flow(),
        str(ARCH_DIR / "paper_loop_sequence.mmd"): render_paper_loop(),
        str(ARCH_DIR / "manifest.json"): json.dumps(
            {
                "schema_version": SCHEMA_VERSION,
                "generator": GENERATOR,
                "source_root": "src",
                "module_count": len(modules),
                "modules": sorted(modules),
                "package_edges": [
                    {"src": s, "dst": d, "imports": c} for (s, d), c in sorted(edges.items())
                ],
                "module_edges": [{"src": s, "dst": d} for (s, d) in sorted(module_edges)],
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
    }


def generated_blocks(artifacts: dict[str, str]) -> dict[str, str]:
    """Atlas-doc embed blocks keyed by marker name."""
    return {
        "module_deps": "```mermaid\n" + artifacts[str(ARCH_DIR / "module_deps.mmd")] + "```",
        "data_flow": "```mermaid\n" + artifacts[str(ARCH_DIR / "data_flow.mmd")] + "```",
        "paper_loop": "```mermaid\n" + artifacts[str(ARCH_DIR / "paper_loop_sequence.mmd")] + "```",
        "coverage": render_coverage(
            json.loads(artifacts[str(ARCH_DIR / "manifest.json")])["modules"],
            Counter(
                {
                    (e["src"], e["dst"]): e["imports"]
                    for e in json.loads(artifacts[str(ARCH_DIR / "manifest.json")])["package_edges"]
                }
            ),
        ),
    }


def splice_blocks(text: str, blocks: dict[str, str]) -> str:
    """Replace ``BEGIN/END GENERATED: name`` marker regions with fresh content."""
    out = text
    for name, body in blocks.items():
        begin = f"<!-- BEGIN GENERATED: {name} -->"
        end = f"<!-- END GENERATED: {name} -->"
        i = out.find(begin)
        j = out.find(end)
        if i < 0 or j < 0 or j < i:
            raise ValueError(f"atlas doc is missing marker pair for {name!r}")
        out = out[: i + len(begin)] + "\n" + body + "\n" + out[j:]
    return out


def write_all(root: Path) -> list[str]:
    errors = verify_anchors(root)
    if errors:
        raise SystemExit("anchor verification failed:\n" + "\n".join(errors))
    artifacts = generated_artifacts(root)
    written: list[str] = []
    for rel, content in artifacts.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(rel)
    atlas = root / ATLAS_DOC
    if atlas.is_file():
        text = splice_blocks(atlas.read_text(encoding="utf-8"), generated_blocks(artifacts))
        atlas.write_text(text, encoding="utf-8")
        written.append(str(ATLAS_DOC))
    return written


def stale_artifacts(root: Path) -> list[str]:
    """Return sorted repo-relative paths whose committed bytes differ from fresh."""
    errors = verify_anchors(root)
    if errors:
        raise SystemExit("anchor verification failed:\n" + "\n".join(errors))
    artifacts = generated_artifacts(root)
    stale: list[str] = []
    for rel, content in artifacts.items():
        path = root / rel
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            stale.append(rel)
    atlas = root / ATLAS_DOC
    if atlas.is_file():
        try:
            expected = splice_blocks(atlas.read_text(encoding="utf-8"), generated_blocks(artifacts))
        except ValueError:
            stale.append(str(ATLAS_DOC))
        else:
            if atlas.read_text(encoding="utf-8") != expected:
                stale.append(str(ATLAS_DOC))
    else:
        stale.append(str(ATLAS_DOC))
    return sorted(stale)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify committed artifacts are fresh")
    parser.add_argument("--stats", action="store_true", help="print scan stats as JSON")
    parser.add_argument(
        "--root", type=Path, default=None, help="repo root (default: script parent)"
    )
    args = parser.parse_args(argv)
    root = (args.root or repo_root()).resolve()

    if args.stats:
        modules, edges, module_edges = collect_graph(root)
        print(
            json.dumps(
                {
                    "modules": len(modules),
                    "packages": len({package_of(m) for m in modules}),
                    "cross_package_edges": sum(1 for (s, d) in edges if s != d),
                    "module_edges": len(module_edges),
                    "distinct_imports": sum(edges.values()),
                },
                sort_keys=True,
            )
        )
        return 0

    if args.check:
        stale = stale_artifacts(root)
        if stale:
            print("stale architecture artifacts — run `python scripts/gen_arch_diagrams.py`:")
            for rel in stale:
                print(f"  {rel}")
            return 1
        print("architecture diagrams are fresh")
        return 0

    written = write_all(root)
    for rel in written:
        print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
